### ISSUE TITLE
Crash on rs_shutdown()

### ISSUE THREAD

**Issue by mbechard** [disguise-one/RenderStream#32]
Often (but not 100% of the time) I get a crash inside of rs_shutdown() when trying to close my app. The call stack is:

Exception thrown at 0x00007FF9CA66D1AB (nvcuda64.dll) in TouchDesigner.exe: 0xC0000005: Access violation writing location 0x0000000000000010.
 	nvcuda64.dll!00007ff9ca66d1ab()	Unknown
 	nvcuda64.dll!00007ff9ca61aecc()	Unknown
 	cudart64_101.dll!00007ffa31b9755a()	Unknown
 	cudart64_101.dll!00007ffa31bb588c()	Unknown
 	blip_gpgpu.dll!00007ffa2fc62ac2()	Unknown
 	blip_gpgpu.dll!00007ffa2fc5448f()	Unknown
 	d3renderstream.dll!00007ffa081e9f3a()	Unknown
 	d3renderstream.dll!00007ffa081cdf05()	Unknown
 	d3renderstream.dll!00007ffa081d9a7a()	Unknown
 	d3renderstream.dll!00007ffa081e94b7()	Unknown
>	libRS.dll!RS_Common::~RS_Common() Line 209	C++

Any ideas what could be causing this? My GL and CUDA context havn't been cleaned up yet at this point during shutdown.

**Comment by husberg-disguise** [comment]
The interop resources were being unregistered on the background thread in the wrong OpenGL context which appears to've gotten CUDA in a bad state causing an access violation when trying to unregister the resource again on the main thread.

Logged and fixed internally as DSOF-20341. Should be fixed in the next hotfix release of d3 (r21.0.3 unless QA find something wrong with it)
